### ISSUE TITLE
Private Messages

### ISSUE THREAD

**Issue by DickerPeter** [Hitmare/unlock-PTB#2]
Good day,

A short question is the release only for channels or also for private messages to the bot?

**Comment by Hitmare** [comment]
Basically its Capable of private and group Chats. 

You just have to adjust the Check in the Command file if the Chat is unlocked. 

I'm doing some changes right now an will add this Case into the Readme/Wiki

**Comment by DickerPeter** [comment]
Thanks for the installation for the function with the private messages.

Other short question.
If you had a finished example for a command.

I have tried it at the command / date from the examples to install but unfortunately does not work so correctly.

**Comment by Hitmare** [comment]
What error occurs ?

**Comment by DickerPeter** [comment]
After installation, he does not accept any commands.

**Comment by Hitmare** [comment]
Are you using a Privat or Group Chat ? Does your Webserver PHP Error log file contain new errors ?

**Comment by Hitmare** [comment]
I'm using the Unlock function here 

https://pastebin.com/tj2yF8rB

**Comment by Hitmare** [comment]
So i have installed a complete new bot with this unlock Library. @HitmareDevBot
I followed the Readme which i wrote and i could lock and unlock the `/date` command without any Problems.

Did you import the SQL file ?
